// The Black Knight: Beginnings

#include "BKEnemyCharacter.h"

#include "AIController.h"
#include "BKEnemyAIController.h"
#include "BKEnemyHealthBarWidget.h"
#include "BrainComponent.h"
#include "BehaviorTree/BehaviorTree.h"
#include "Components/CapsuleComponent.h"
#include "Components/WidgetComponent.h"
#include "UObject/ConstructorHelpers.h"

ABKEnemyCharacter::ABKEnemyCharacter(const FObjectInitializer& ObjectInitializer) : Super{ObjectInitializer}
{
	HealthBarWidget = CreateDefaultSubobject<UWidgetComponent>(TEXT("HealthBar"));
	HealthBarWidget->SetupAttachment(GetCapsuleComponent());
	HealthBarWidget->SetRelativeLocation(FVector{0.0, 0.0, 115.0});
	HealthBarWidget->SetWidgetSpace(EWidgetSpace::Screen);
	HealthBarWidget->SetDrawSize(FVector2D{110.0, 8.0});
	HealthBarWidget->SetWidgetClass(UBKEnemyHealthBarWidget::StaticClass());
	HealthBarWidget->SetCollisionEnabled(ECollisionEnabled::NoCollision);

	AIControllerClass = ABKEnemyAIController::StaticClass();
	AutoPossessAI = EAutoPossessAI::PlacedInWorldOrSpawned;

	// Generated by BKCreateEnemyAICommandlet (Source/BlackKnight/Editor).
	static ConstructorHelpers::FObjectFinder<UBehaviorTree> BehaviorTreeAsset{TEXT("/Game/AI/BT_BK_Enemy.BT_BK_Enemy")};
	BehaviorTree = BehaviorTreeAsset.Object;
}

void ABKEnemyCharacter::BeginPlay()
{
	Super::BeginPlay();

	if (auto* HealthBar{Cast<UBKEnemyHealthBarWidget>(HealthBarWidget->GetUserWidgetObject())}; IsValid(HealthBar))
	{
		HealthBar->SetOwnerCharacter(this);
	}
}

bool ABKEnemyCharacter::StartAIAttack()
{
	const EBKAttackType Type{FMath::FRand() < HeavyAttackChance ? EBKAttackType::Heavy : EBKAttackType::Light};
	const int32 Steps{FMath::RandRange(1, FMath::Min(MaxComboSteps, Melee->GetComboLength(Type)))};

	return TryStartAttackChain(Type, Steps);
}

void ABKEnemyCharacter::HandleDeath()
{
	if (auto* AIController{Cast<AAIController>(GetController())}; IsValid(AIController))
	{
		if (auto* Brain{AIController->GetBrainComponent()}; IsValid(Brain))
		{
			Brain->StopLogic(TEXT("Dead"));
		}
		AIController->ClearFocus(EAIFocusPriority::Gameplay);
	}

	Super::HandleDeath();

	DetachFromControllerPendingDestroy();
	SetLifeSpan(CorpseLifeSpan);
}
