// The Black Knight: Beginnings

#include "BKPlayerCharacter.h"

#include "BlackKnight.h"
#include "BKCameraComponent.h"
#include "BKCombatTags.h"
#include "BKHealthComponent.h"
#include "BKStaminaComponent.h"
#include "DisplayDebugHelpers.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "InputAction.h"
#include "InputMappingContext.h"
#include "Animation/AnimInstance.h"
#include "Animation/AnimMontage.h"
#include "Components/SkeletalMeshComponent.h"
#include "Engine/Canvas.h"
#include "Engine/LocalPlayer.h"
#include "GameFramework/PlayerController.h"
#include "TimerManager.h"
#include "UObject/ConstructorHelpers.h"
#include "Utility/AlsGameplayTags.h"
#include "Utility/AlsVector.h"

namespace BKPlayerInputAssets
{
	const TCHAR* const MappingContext{TEXT("/ALS/ALS/Data/Input/IMC_Als_Default.IMC_Als_Default")};
	const TCHAR* const Move{TEXT("/ALS/ALS/Data/Input/IA_Als_Move.IA_Als_Move")};
	const TCHAR* const LookMouse{TEXT("/ALS/ALS/Data/Input/IA_Als_LookMouse.IA_Als_LookMouse")};
	const TCHAR* const Look{TEXT("/ALS/ALS/Data/Input/IA_Als_Look.IA_Als_Look")};
	const TCHAR* const Jump{TEXT("/ALS/ALS/Data/Input/IA_Als_Jump.IA_Als_Jump")};
	const TCHAR* const Sprint{TEXT("/ALS/ALS/Data/Input/IA_Als_Sprint.IA_Als_Sprint")};
	const TCHAR* const Walk{TEXT("/ALS/ALS/Data/Input/IA_Als_Walk.IA_Als_Walk")};
	const TCHAR* const Crouch{TEXT("/ALS/ALS/Data/Input/IA_Als_Crouch.IA_Als_Crouch")};
	const TCHAR* const Roll{TEXT("/ALS/ALS/Data/Input/IA_Als_Roll.IA_Als_Roll")};

	// Black Knight-authored content, generated by BKCreateCombatInputAssetsCommandlet
	// (Source/BlackKnight/Editor). Re-run that commandlet if these paths ever change.
	const TCHAR* const CombatMappingContext{TEXT("/Game/Input/IMC_BK_Combat.IMC_BK_Combat")};
	const TCHAR* const Block{TEXT("/Game/Input/IA_BK_Block.IA_BK_Block")};
	const TCHAR* const LightAttack{TEXT("/Game/Input/IA_BK_LightAttack.IA_BK_LightAttack")};
	const TCHAR* const HeavyAttack{TEXT("/Game/Input/IA_BK_HeavyAttack.IA_BK_HeavyAttack")};
	const TCHAR* const LockOn{TEXT("/Game/Input/IA_BK_LockOn.IA_BK_LockOn")};
}

ABKPlayerCharacter::ABKPlayerCharacter(const FObjectInitializer& ObjectInitializer) : Super{ObjectInitializer}
{
	Camera = CreateDefaultSubobject<UBKCameraComponent>(TEXT("Camera"));
	Camera->SetupAttachment(GetMesh());
	Camera->SetRelativeRotation_Direct({0.0f, 90.0f, 0.0f});

	Stamina = CreateDefaultSubobject<UBKStaminaComponent>(TEXT("Stamina"));

	// Generated by BKCreateCombatAnimationsCommandlet (Source/BlackKnight/Editor).
	static ConstructorHelpers::FObjectFinder<UAnimMontage> BlockMontageAsset{TEXT("/Game/Combat/Animations/AM_BK_Block.AM_BK_Block")};
	BlockMontage = BlockMontageAsset.Object;

	static ConstructorHelpers::FObjectFinder<UInputMappingContext> MappingContextAsset{BKPlayerInputAssets::MappingContext};
	static ConstructorHelpers::FObjectFinder<UInputMappingContext> CombatMappingContextAsset{BKPlayerInputAssets::CombatMappingContext};
	static ConstructorHelpers::FObjectFinder<UInputAction> MoveAsset{BKPlayerInputAssets::Move};
	static ConstructorHelpers::FObjectFinder<UInputAction> LookMouseAsset{BKPlayerInputAssets::LookMouse};
	static ConstructorHelpers::FObjectFinder<UInputAction> LookAsset{BKPlayerInputAssets::Look};
	static ConstructorHelpers::FObjectFinder<UInputAction> JumpAsset{BKPlayerInputAssets::Jump};
	static ConstructorHelpers::FObjectFinder<UInputAction> SprintAsset{BKPlayerInputAssets::Sprint};
	static ConstructorHelpers::FObjectFinder<UInputAction> WalkAsset{BKPlayerInputAssets::Walk};
	static ConstructorHelpers::FObjectFinder<UInputAction> CrouchAsset{BKPlayerInputAssets::Crouch};
	static ConstructorHelpers::FObjectFinder<UInputAction> RollAsset{BKPlayerInputAssets::Roll};
	static ConstructorHelpers::FObjectFinder<UInputAction> BlockAsset{BKPlayerInputAssets::Block};
	static ConstructorHelpers::FObjectFinder<UInputAction> LightAttackAsset{BKPlayerInputAssets::LightAttack};
	static ConstructorHelpers::FObjectFinder<UInputAction> HeavyAttackAsset{BKPlayerInputAssets::HeavyAttack};
	static ConstructorHelpers::FObjectFinder<UInputAction> LockOnAsset{BKPlayerInputAssets::LockOn};

	InputMappingContext = MappingContextAsset.Object;
	CombatInputMappingContext = CombatMappingContextAsset.Object;
	MoveAction = MoveAsset.Object;
	LookMouseAction = LookMouseAsset.Object;
	LookAction = LookAsset.Object;
	JumpAction = JumpAsset.Object;
	SprintAction = SprintAsset.Object;
	WalkAction = WalkAsset.Object;
	CrouchAction = CrouchAsset.Object;
	RollAction = RollAsset.Object;
	BlockAction = BlockAsset.Object;
	LightAttackAction = LightAttackAsset.Object;
	HeavyAttackAction = HeavyAttackAsset.Object;
	LockOnAction = LockOnAsset.Object;
}

void ABKPlayerCharacter::BeginPlay()
{
	Super::BeginPlay();

	Camera->OnLockOnTargetChanged.AddUObject(this, &ThisClass::OnLockOnTargetChanged);
}

void ABKPlayerCharacter::NotifyControllerChanged()
{
	const auto* PreviousPlayer{Cast<APlayerController>(PreviousController)};
	if (IsValid(PreviousPlayer))
	{
		auto* InputSubsystem{ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PreviousPlayer->GetLocalPlayer())};
		if (IsValid(InputSubsystem))
		{
			InputSubsystem->RemoveMappingContext(InputMappingContext);
			InputSubsystem->RemoveMappingContext(CombatInputMappingContext);
		}
	}

	auto* NewPlayer{Cast<APlayerController>(GetController())};
	if (IsValid(NewPlayer))
	{
		// ALS applies its own look sensitivity, so neutralize the legacy scales.

		NewPlayer->InputYawScale_DEPRECATED = 1.0f;
		NewPlayer->InputPitchScale_DEPRECATED = 1.0f;
		NewPlayer->InputRollScale_DEPRECATED = 1.0f;

		auto* InputSubsystem{ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(NewPlayer->GetLocalPlayer())};
		if (IsValid(InputSubsystem))
		{
			FModifyContextOptions Options;
			Options.bNotifyUserSettings = true;

			InputSubsystem->AddMappingContext(InputMappingContext, 0, Options);
			InputSubsystem->AddMappingContext(CombatInputMappingContext, 1, Options);
		}
	}

	Super::NotifyControllerChanged();
}

void ABKPlayerCharacter::Tick(const float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (!IsAlive())
	{
		return;
	}

	// Holding the guard up costs stamina on its own; a dry guard collapses.
	if (bIsBlocking)
	{
		Stamina->DrainStamina(BlockStaminaPerSecond * DeltaTime);
		if (Stamina->IsDepleted())
		{
			BreakGuard();
		}
	}

	// Sprinting costs stamina only while actually moving at a sprint.
	if (GetGait() == AlsGaitTags::Sprinting && GetLocomotionState().bMoving)
	{
		Stamina->DrainStamina(SprintStaminaPerSecond * DeltaTime);
		if (Stamina->IsDepleted())
		{
			bSprintExhausted = true;
			RefreshSprintGait();
		}
	}
	else if (bSprintExhausted && Stamina->HasStamina(SprintResumeStamina))
	{
		bSprintExhausted = false;
		RefreshSprintGait();
	}
}

void ABKPlayerCharacter::RefreshSprintGait()
{
	const bool bCanSprint{bWantsToSprint && !bSprintExhausted && !Stamina->IsDepleted()};
	if (bCanSprint && GetDesiredGait() != AlsGaitTags::Sprinting)
	{
		SetDesiredGait(AlsGaitTags::Sprinting);
	}
	else if (!bCanSprint && GetDesiredGait() == AlsGaitTags::Sprinting)
	{
		SetDesiredGait(AlsGaitTags::Running);
	}
}

void ABKPlayerCharacter::CalcCamera(const float DeltaTime, FMinimalViewInfo& ViewInfo)
{
	if (Camera->IsActive())
	{
		Camera->GetViewInfo(ViewInfo);
		return;
	}

	Super::CalcCamera(DeltaTime, ViewInfo);
}

void ABKPlayerCharacter::SetupPlayerInputComponent(UInputComponent* Input)
{
	Super::SetupPlayerInputComponent(Input);

	auto* EnhancedInput{Cast<UEnhancedInputComponent>(Input)};
	if (!IsValid(EnhancedInput))
	{
		return;
	}

	EnhancedInput->BindAction(MoveAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnMove);
	EnhancedInput->BindAction(MoveAction, ETriggerEvent::Canceled, this, &ThisClass::Input_OnMove);
	EnhancedInput->BindAction(LookMouseAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnLookMouse);
	EnhancedInput->BindAction(LookMouseAction, ETriggerEvent::Canceled, this, &ThisClass::Input_OnLookMouse);
	EnhancedInput->BindAction(LookAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnLook);
	EnhancedInput->BindAction(LookAction, ETriggerEvent::Canceled, this, &ThisClass::Input_OnLook);
	EnhancedInput->BindAction(JumpAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnJump);
	EnhancedInput->BindAction(JumpAction, ETriggerEvent::Canceled, this, &ThisClass::Input_OnJump);
	EnhancedInput->BindAction(SprintAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnSprint);
	EnhancedInput->BindAction(SprintAction, ETriggerEvent::Canceled, this, &ThisClass::Input_OnSprint);
	EnhancedInput->BindAction(WalkAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnWalk);
	EnhancedInput->BindAction(CrouchAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnCrouch);
	EnhancedInput->BindAction(RollAction, ETriggerEvent::Triggered, this, &ThisClass::Input_OnRoll);
	EnhancedInput->BindAction(BlockAction, ETriggerEvent::Started, this, &ThisClass::Input_OnBlockStart);
	EnhancedInput->BindAction(BlockAction, ETriggerEvent::Completed, this, &ThisClass::Input_OnBlockEnd);
	EnhancedInput->BindAction(BlockAction, ETriggerEvent::Canceled, this, &ThisClass::Input_OnBlockEnd);
	EnhancedInput->BindAction(LightAttackAction, ETriggerEvent::Started, this, &ThisClass::Input_OnLightAttack);
	EnhancedInput->BindAction(HeavyAttackAction, ETriggerEvent::Started, this, &ThisClass::Input_OnHeavyAttack);
	EnhancedInput->BindAction(LockOnAction, ETriggerEvent::Started, this, &ThisClass::Input_OnLockOn);
}

void ABKPlayerCharacter::Input_OnMove(const FInputActionValue& ActionValue)
{
	// Dead, committed to a swing, reeling from a stagger, or planted behind the guard: no steering.
	// (Blocking is a full-body pose - see BuildBlockMontage - so moving while blocking would slide.)
	if (!IsAlive() || bIsBlocking || GetLocomotionAction() == BKLocomotionActionTags::Attacking ||
	    GetLocomotionAction() == BKLocomotionActionTags::Staggered)
	{
		return;
	}

	const auto Value{UAlsVector::ClampMagnitude012D(ActionValue.Get<FVector2D>())};

	auto ViewRotation{GetViewState().Rotation};

	if (IsValid(GetController()))
	{
		// Prefer the exact camera rotation over the interpolated target rotation.

		FVector ViewLocation;
		GetController()->GetPlayerViewPoint(ViewLocation, ViewRotation);
	}

	const auto ForwardDirection{UAlsVector::AngleToDirectionXY(UE_REAL_TO_FLOAT(ViewRotation.Yaw))};
	const auto RightDirection{UAlsVector::PerpendicularCounterClockwiseXY(ForwardDirection)};

	AddMovementInput(ForwardDirection * Value.Y + RightDirection * Value.X);
}

void ABKPlayerCharacter::Input_OnLookMouse(const FInputActionValue& ActionValue)
{
	if (IsValid(Camera->GetLockOnTarget()))
	{
		return;
	}

	const FVector2f Value{ActionValue.Get<FVector2D>()};

	AddControllerPitchInput(Value.Y * LookUpMouseSensitivity);
	AddControllerYawInput(Value.X * LookRightMouseSensitivity);
}

void ABKPlayerCharacter::Input_OnLook(const FInputActionValue& ActionValue)
{
	if (IsValid(Camera->GetLockOnTarget()))
	{
		return;
	}

	const FVector2f Value{ActionValue.Get<FVector2D>()};

	AddControllerPitchInput(Value.Y * LookUpRate);
	AddControllerYawInput(Value.X * LookRightRate);
}

void ABKPlayerCharacter::Input_OnJump(const FInputActionValue& ActionValue)
{
	// ALS binds "get up from ragdoll" to jump; a dead player must stay down.
	if (!IsAlive())
	{
		return;
	}

	if (!ActionValue.Get<bool>())
	{
		StopJumping();
		return;
	}

	if (StopRagdolling())
	{
		return;
	}

	if (StartMantling())
	{
		return;
	}

	if (GetStance() == AlsStanceTags::Crouching)
	{
		SetDesiredStance(AlsStanceTags::Standing);
		return;
	}

	Jump();
}

void ABKPlayerCharacter::Input_OnSprint(const FInputActionValue& ActionValue)
{
	bWantsToSprint = ActionValue.Get<bool>();
	RefreshSprintGait();
}

void ABKPlayerCharacter::Input_OnWalk()
{
	if (GetDesiredGait() == AlsGaitTags::Walking)
	{
		SetDesiredGait(AlsGaitTags::Running);
	}
	else if (GetDesiredGait() == AlsGaitTags::Running)
	{
		SetDesiredGait(AlsGaitTags::Walking);
	}
}

void ABKPlayerCharacter::Input_OnCrouch()
{
	if (GetDesiredStance() == AlsStanceTags::Standing)
	{
		SetDesiredStance(AlsStanceTags::Crouching);
	}
	else if (GetDesiredStance() == AlsStanceTags::Crouching)
	{
		SetDesiredStance(AlsStanceTags::Standing);
	}
}

void ABKPlayerCharacter::Input_OnRoll()
{
	static constexpr auto PlayRate{1.3f};

	// Refuse up front so we don't spend stamina or open an i-frame window for a roll
	// ALS is about to reject anyway (see CanStartCombatAction).
	if (!CanStartCombatAction() || !Stamina->TryConsumeStamina(RollStaminaCost))
	{
		return;
	}

	StartRollingGrounded(PlayRate);
	BeginInvulnerabilityWindow(RollInvulnerabilityDuration);
}

void ABKPlayerCharacter::Input_OnBlockStart()
{
	if (bIsBlocking || !CanStartCombatAction() || Stamina->IsDepleted())
	{
		return;
	}

	bIsBlocking = true;
	bInPerfectBlockWindow = true;
	SetLocomotionAction(BKLocomotionActionTags::Blocking);

	GetWorldTimerManager().SetTimer(PerfectBlockWindowTimerHandle, this, &ThisClass::EndPerfectBlockWindow, PerfectBlockWindow, false);

	if (auto* AnimInstance{GetMesh()->GetAnimInstance()}; IsValid(AnimInstance) && IsValid(BlockMontage))
	{
		const float PlayLength{AnimInstance->Montage_Play(BlockMontage)};
		UE_LOG(LogBlackKnight, Verbose, TEXT("%s: block montage play = %.3f (length %.3f, group %s, slots %d)"),
		       *GetName(), PlayLength, BlockMontage->GetPlayLength(), *BlockMontage->GetGroupName().ToString(),
		       BlockMontage->SlotAnimTracks.Num());
	}
}

void ABKPlayerCharacter::Input_OnBlockEnd()
{
	if (!bIsBlocking)
	{
		return;
	}

	bIsBlocking = false;
	bInPerfectBlockWindow = false;
	GetWorldTimerManager().ClearTimer(PerfectBlockWindowTimerHandle);

	if (auto* AnimInstance{GetMesh()->GetAnimInstance()}; IsValid(AnimInstance) && IsValid(BlockMontage))
	{
		AnimInstance->Montage_Stop(BlockMontage->BlendOut.GetBlendTime(), BlockMontage);
	}

	if (GetLocomotionAction() == BKLocomotionActionTags::Blocking)
	{
		SetLocomotionAction(FGameplayTag::EmptyTag);
	}
}

void ABKPlayerCharacter::BreakGuard()
{
	Input_OnBlockEnd();
	OnGuardBroken.Broadcast();

	UE_LOG(LogTemp, Log, TEXT("%s: guard broken"), *GetName());
}

void ABKPlayerCharacter::Input_OnLightAttack()
{
	TryStartAttack(EBKAttackType::Light);
}

void ABKPlayerCharacter::Input_OnHeavyAttack()
{
	TryStartAttack(EBKAttackType::Heavy);
}

void ABKPlayerCharacter::Input_OnLockOn()
{
	if (IsValid(Camera->GetLockOnTarget()))
	{
		Camera->ClearLockOn();
	}
	else
	{
		Camera->TryLockOn();
	}
}

void ABKPlayerCharacter::OnLockOnTargetChanged(AActor* NewTarget)
{
	if (IsValid(NewTarget))
	{
		// Only remember the pre-lock mode on the transition into lock-on, not when switching targets.
		if (!RotationModeBeforeLockOn.IsValid())
		{
			RotationModeBeforeLockOn = GetDesiredRotationMode();
		}
		SetDesiredRotationMode(AlsRotationModeTags::ViewDirection);
	}
	else if (RotationModeBeforeLockOn.IsValid())
	{
		SetDesiredRotationMode(RotationModeBeforeLockOn);
		RotationModeBeforeLockOn = FGameplayTag::EmptyTag;
	}
}

void ABKPlayerCharacter::BeginInvulnerabilityWindow(const float Duration)
{
	bIsInvulnerable = true;
	GetWorldTimerManager().SetTimer(InvulnerabilityTimerHandle, this, &ThisClass::EndInvulnerabilityWindow, Duration, false);
}

void ABKPlayerCharacter::EndInvulnerabilityWindow()
{
	bIsInvulnerable = false;
}

void ABKPlayerCharacter::EndPerfectBlockWindow()
{
	bInPerfectBlockWindow = false;
}

void ABKPlayerCharacter::HandleDeath()
{
	Input_OnBlockEnd();
	Camera->ClearLockOn();

	Super::HandleDeath();
}

void ABKPlayerCharacter::ApplyDamage(const float Damage, AActor* DamageCauser, const FVector& HitLocation, const FVector& HitImpulse)
{
	if (!IsDamageable() || Damage <= 0.0f)
	{
		return;
	}

	if (bIsBlocking)
	{
		if (bInPerfectBlockWindow)
		{
			// Perfect Block: no damage, no stamina cost, punish the attacker.
			if (auto* Attacker{Cast<IBKDamageable>(DamageCauser)}; Attacker != nullptr)
			{
				Attacker->ApplyStagger(PerfectBlockStaggerDuration, this);
			}
			PlayHitEffects(HitLocation, true);
			OnPerfectBlock.Broadcast();
			return;
		}

		Stamina->DrainStamina(Damage * BlockStaminaCostPerDamage);

		if (!Stamina->IsDepleted())
		{
			Super::ApplyDamage(Damage * (1.0f - BlockDamageMitigation), DamageCauser, HitLocation, HitImpulse);
			return;
		}

		// Guard break: the block collapses and this hit gets through unmitigated.
		BreakGuard();
	}

	Super::ApplyDamage(Damage, DamageCauser, HitLocation, HitImpulse);
}

void ABKPlayerCharacter::ApplyStagger(const float Duration, AActor* StaggerInstigator)
{
	if (!IsDamageable())
	{
		return;
	}

	Input_OnBlockEnd();
	Super::ApplyStagger(Duration, StaggerInstigator);
}

bool ABKPlayerCharacter::IsDamageable() const
{
	return Super::IsDamageable() && !bIsInvulnerable;
}

void ABKPlayerCharacter::DisplayDebug(UCanvas* Canvas, const FDebugDisplayInfo& DisplayInfo,
                                      float& Unused, float& VerticalLocation)
{
	if (Camera->IsActive())
	{
		Camera->DisplayDebug(Canvas, DisplayInfo, VerticalLocation);
	}

	if (DisplayInfo.IsDisplayOn(TEXT("Combat")))
	{
		auto& DisplayDebugManager{Canvas->DisplayDebugManager};
		DisplayDebugManager.SetDrawColor(FColor::White);
		DisplayDebugManager.DrawString(FString::Printf(
			TEXT("Health: %.0f / %.0f    Stamina: %.0f / %.0f    Blocking: %s%s    Invulnerable: %s"),
			Health->GetCurrentHealth(), Health->GetMaxHealth(),
			Stamina->GetCurrentStamina(), Stamina->GetMaxStamina(),
			bIsBlocking ? TEXT("Yes") : TEXT("No"),
			bInPerfectBlockWindow ? TEXT(" (Perfect window)") : TEXT(""),
			bIsInvulnerable ? TEXT("Yes") : TEXT("No")));

		const auto AttackName{Melee->GetCurrentAttack() == EBKAttackType::Light ? TEXT("Light")
		                      : Melee->GetCurrentAttack() == EBKAttackType::Heavy ? TEXT("Heavy") : TEXT("None")};
		DisplayDebugManager.DrawString(FString::Printf(
			TEXT("Attack: %s (step %d / %d)    Lock-on: %s    Action: %s"),
			AttackName, Melee->GetComboIndex() + 1, Melee->GetComboLength(Melee->GetCurrentAttack()),
			*GetNameSafe(Camera->GetLockOnTarget()),
			*GetLocomotionAction().ToString()));

		VerticalLocation = DisplayDebugManager.GetYPos();
	}

	Super::DisplayDebug(Canvas, DisplayInfo, Unused, VerticalLocation);
}
