// The Black Knight: Beginnings

#include "BKMeleeComponent.h"

#include "BKDamageable.h"
#include "BKStaminaComponent.h"
#include "Animation/AnimInstance.h"
#include "Animation/AnimMontage.h"
#include "Components/SkeletalMeshComponent.h"
#include "Engine/World.h"
#include "GameFramework/Character.h"
#include "UObject/ConstructorHelpers.h"

namespace BKMeleeDefaults
{
	// Montages generated by BKCreateCombatAnimationsCommandlet (Source/BlackKnight/Editor).
	struct FStepDefault
	{
		const TCHAR* MontagePath;
		float Damage;
		float StaminaCost;
	};

	constexpr FStepDefault LightSteps[]{
		{TEXT("/Game/Combat/Animations/AM_BK_Light_01.AM_BK_Light_01"), 12.0f, 10.0f},
		{TEXT("/Game/Combat/Animations/AM_BK_Light_02.AM_BK_Light_02"), 12.0f, 10.0f},
		{TEXT("/Game/Combat/Animations/AM_BK_Light_03.AM_BK_Light_03"), 14.0f, 10.0f},
		{TEXT("/Game/Combat/Animations/AM_BK_Light_04.AM_BK_Light_04"), 20.0f, 14.0f},
	};

	constexpr FStepDefault HeavySteps[]{
		{TEXT("/Game/Combat/Animations/AM_BK_Heavy_01.AM_BK_Heavy_01"), 28.0f, 22.0f},
		{TEXT("/Game/Combat/Animations/AM_BK_Heavy_02.AM_BK_Heavy_02"), 34.0f, 24.0f},
		{TEXT("/Game/Combat/Animations/AM_BK_Heavy_03.AM_BK_Heavy_03"), 50.0f, 30.0f},
	};
}

UBKMeleeComponent::UBKMeleeComponent()
{
	PrimaryComponentTick.bCanEverTick = false;

	const auto LoadSteps{[](const TConstArrayView<BKMeleeDefaults::FStepDefault> Defaults, TArray<FBKAttackStep>& OutSteps)
	{
		for (const BKMeleeDefaults::FStepDefault& Default : Defaults)
		{
			FBKAttackStep& Step{OutSteps.AddDefaulted_GetRef()};
			Step.Montage = ConstructorHelpers::FObjectFinder<UAnimMontage>{Default.MontagePath}.Object;
			Step.Damage = Default.Damage;
			Step.StaminaCost = Default.StaminaCost;
		}
	}};

	LoadSteps(BKMeleeDefaults::LightSteps, LightCombo);
	LoadSteps(BKMeleeDefaults::HeavySteps, HeavyCombo);
}

void UBKMeleeComponent::BeginPlay()
{
	Super::BeginPlay();

	Stamina = GetOwner()->FindComponentByClass<UBKStaminaComponent>();
}

const TArray<FBKAttackStep>& UBKMeleeComponent::GetCombo(const EBKAttackType Type) const
{
	return Type == EBKAttackType::Heavy ? HeavyCombo : LightCombo;
}

const FBKAttackStep* UBKMeleeComponent::GetCurrentStep() const
{
	const TArray<FBKAttackStep>& Combo{GetCombo(CurrentAttack)};
	return IsAttacking() && Combo.IsValidIndex(ComboIndex) ? &Combo[ComboIndex] : nullptr;
}

bool UBKMeleeComponent::StartAttack(const EBKAttackType Type)
{
	if (Type == EBKAttackType::None)
	{
		return false;
	}

	if (IsAttacking())
	{
		if (Type == CurrentAttack)
		{
			LastAttackInputTime = GetWorld()->GetTimeSeconds();
		}
		return false;
	}

	QueuedChainSteps = 0;
	return PlayStep(Type, 0);
}

bool UBKMeleeComponent::StartAttackChain(const EBKAttackType Type, const int32 NumSteps)
{
	if (Type == EBKAttackType::None || IsAttacking() || !PlayStep(Type, 0))
	{
		return false;
	}

	QueuedChainSteps = FMath::Max(0, NumSteps - 1);
	return true;
}

bool UBKMeleeComponent::PlayStep(const EBKAttackType Type, const int32 Index)
{
	const TArray<FBKAttackStep>& Combo{GetCombo(Type)};
	auto* AnimInstance{GetOwnerAnimInstance()};
	if (!Combo.IsValidIndex(Index) || !IsValid(Combo[Index].Montage) || !IsValid(AnimInstance))
	{
		return false;
	}

	const FBKAttackStep& Step{Combo[Index]};

	if (IsValid(Stamina) && !Stamina->HasStamina(Step.StaminaCost))
	{
		return false;
	}

	// Playing the next step stops the previous one, which blends out underneath it.
	if (AnimInstance->Montage_Play(Step.Montage) <= 0.0f)
	{
		return false;
	}

	if (IsValid(Stamina))
	{
		Stamina->TryConsumeStamina(Step.StaminaCost);
	}

	CurrentAttack = Type;
	ComboIndex = Index;
	LastAttackInputTime = -1000.0;
	StepStartTime = GetWorld()->GetTimeSeconds();
	bStepImpactPassed = false;
	ActorsHitThisStep.Reset();
	++AttackSerial;

	FOnMontageBlendingOutStarted BlendingOutDelegate;
	BlendingOutDelegate.BindUObject(this, &ThisClass::OnMontageBlendingOut, AttackSerial);
	AnimInstance->Montage_SetBlendingOutDelegate(BlendingOutDelegate, Step.Montage);

	OnAttackStepStarted.Broadcast(Type, Index);

	return true;
}

void UBKMeleeComponent::CancelAttack()
{
	const FBKAttackStep* Step{GetCurrentStep()};
	if (Step == nullptr)
	{
		return;
	}

	if (auto* AnimInstance{GetOwnerAnimInstance()}; IsValid(AnimInstance))
	{
		AnimInstance->Montage_Stop(0.2f, Step->Montage);
	}

	// The montage's blend-out callback is queued until the next animation update; end the attack now.
	CurrentAttack = EBKAttackType::None;
	QueuedChainSteps = 0;
	StepStartTime = -1.0;
	OnAttackEnded.Broadcast(true);
}

void UBKMeleeComponent::OnMontageBlendingOut(UAnimMontage*, const bool bInterrupted, const int32 Serial)
{
	if (Serial != AttackSerial || !IsAttacking())
	{
		return;
	}

	CurrentAttack = EBKAttackType::None;
	QueuedChainSteps = 0;
	StepStartTime = -1.0;
	OnAttackEnded.Broadcast(bInterrupted);
}

void UBKMeleeComponent::DoAttackTrace(const FName SourceBone, const UAnimSequenceBase* Animation)
{
	const FBKAttackStep* Step{GetCurrentStep()};
	const auto* Character{Cast<ACharacter>(GetOwner())};
	if (Step == nullptr || Step->Montage != Animation || !IsValid(Character))
	{
		return;
	}

	// The hit frame has played: from here the swing is committed and stops steering (see ABKCombatCharacter).
	bStepImpactPassed = true;

	const auto* Mesh{Character->GetMesh()};
	const FVector TraceStart{SourceBone.IsNone() ? Character->GetActorLocation() : Mesh->GetSocketLocation(SourceBone)};
	const FVector TraceEnd{TraceStart + Character->GetActorForwardVector() * TraceDistance};

	FCollisionObjectQueryParams ObjectParams;
	ObjectParams.AddObjectTypesToQuery(ECC_Pawn);
	ObjectParams.AddObjectTypesToQuery(ECC_WorldDynamic);

	const FCollisionQueryParams QueryParams{SCENE_QUERY_STAT(BKMeleeAttackTrace), false, Character};

	TArray<FHitResult> Hits;
	if (!GetWorld()->SweepMultiByObjectType(Hits, TraceStart, TraceEnd, FQuat::Identity, ObjectParams,
	                                        FCollisionShape::MakeSphere(TraceRadius), QueryParams))
	{
		return;
	}

	const float Damage{Step->Damage * DamageMultiplier};
	const int32 Serial{AttackSerial};

	for (const FHitResult& Hit : Hits)
	{
		auto* HitActor{Hit.GetActor()};
		auto* Damageable{Cast<IBKDamageable>(HitActor)};
		const TWeakObjectPtr<AActor> HitActorWeak{HitActor};
		if (Damageable == nullptr || !Damageable->IsAlive() || ActorsHitThisStep.Contains(HitActorWeak))
		{
			continue;
		}

		// One actor can return several hit components (capsule + mesh); damage it once.
		ActorsHitThisStep.Add(HitActorWeak);

		Damageable->ApplyDamage(Damage, GetOwner(), Hit.ImpactPoint, -Hit.ImpactNormal * KnockbackImpulse);

		// A Perfect Block staggers us, which cancels this attack; stop dealing damage if so.
		if (Serial != AttackSerial || !IsAttacking())
		{
			return;
		}
	}
}

void UBKMeleeComponent::CheckCombo(const UAnimSequenceBase* Animation)
{
	const FBKAttackStep* Step{GetCurrentStep()};
	if (Step == nullptr || Step->Montage != Animation)
	{
		return;
	}

	const bool bInputBuffered{GetWorld()->GetTimeSeconds() - LastAttackInputTime <= ComboInputBufferTime};
	if (!bInputBuffered && QueuedChainSteps <= 0)
	{
		return;
	}

	const int32 RemainingQueued{QueuedChainSteps};
	if (PlayStep(CurrentAttack, ComboIndex + 1))
	{
		QueuedChainSteps = FMath::Max(0, RemainingQueued - 1);
	}
}

float UBKMeleeComponent::GetTimeSinceStepStarted() const
{
	return StepStartTime < 0.0 ? TNumericLimits<float>::Max()
	                           : UE_REAL_TO_FLOAT(GetWorld()->GetTimeSeconds() - StepStartTime);
}

UAnimInstance* UBKMeleeComponent::GetOwnerAnimInstance() const
{
	const auto* Character{Cast<ACharacter>(GetOwner())};
	return IsValid(Character) && IsValid(Character->GetMesh()) ? Character->GetMesh()->GetAnimInstance() : nullptr;
}
